// SPDX-License-Identifier: AGPL-3.0-only
// GENERATED by tools/generate_mobile.py — edit packages/mobile and packages/design instead.
import Foundation

public enum PreviewSamples {
 public static var stations: [PreviewStation] { [
  PreviewStation(id: "parkside", name: "Petro-Canada", brand: "Petro-Canada", address: "128 Parkway", distanceMetres: 2400, minutes: 6, x: 620, y: 462, open: true, prices: ["regular": 1429, "premium": 1639, "diesel": 1529], ages: ["regular": 7, "premium": 7, "diesel": 7], memberDiscount: 0),
  PreviewStation(id: "northline", name: "Shell", brand: "Shell", address: "640 Cedar Avenue", distanceMetres: 1200, minutes: 3, x: 820, y: 258, open: true, prices: ["regular": 1479, "premium": 1689, "diesel": 1549], ages: ["regular": 12, "premium": 12, "diesel": 12], memberDiscount: 0),
  PreviewStation(id: "juniper", name: "Husky (legacy)", brand: "Husky", address: "82 Birch Street", distanceMetres: 800, minutes: 2, x: 425, y: 319, open: true, prices: ["regular": 1499, "premium": 1729], ages: ["regular": 18, "premium": 18], memberDiscount: 0),
  PreviewStation(id: "westway", name: "Esso", brand: "Esso", address: "905 River Road", distanceMetres: 3100, minutes: 7, x: 780, y: 786, open: true, prices: ["regular": 1529, "premium": 1759, "diesel": 1589], ages: ["regular": 42, "premium": 42, "diesel": 42], memberDiscount: 0),
  PreviewStation(id: "cedar", name: "Mobil", brand: "Mobil", address: "310 Lakeside Road", distanceMetres: 4200, minutes: 9, x: 247, y: 659, open: true, prices: ["regular": 1449, "premium": 1669, "diesel": 1519], ages: ["regular": 180, "premium": 180, "diesel": 180], memberDiscount: 40),
  PreviewStation(id: "loop", name: "Chevron", brand: "Chevron", address: "18 Eastbank Drive", distanceMetres: 3400, minutes: 8, x: 960, y: 543, open: false, prices: ["regular": 1559, "premium": 1799, "diesel": 1629], ages: ["regular": 24, "premium": 24, "diesel": 24], memberDiscount: 0)
 ] }
}

public enum PreviewTokens {
 public static let green: UInt = 0x285B43
 public static let ink: UInt = 0x20392E
 public static let muted: UInt = 0x768077
 public static let line: UInt = 0xE8ECE5
 public static let soft: UInt = 0xF3F5EF
 public static let paper: UInt = 0xFFFFFF
 public static let blue: UInt = 0x4485ED
 public static let best: UInt = 0xF6FAF0
 public static let edge: Double = 16
 public static let rowRadius: Double = 15
 public static let goSize: Double = 48
 public static let goRadius: Double = 14
 public static let searchHeight: Double = 59
 public static let searchRadius: Double = 19
 public static let sheetRadius: Double = 26
 public static let stationName: Double = 14
 public static let priceSize: Double = 24
 public static let stationAge: Double = 9
 public static let rowPadding: Double = 12
}
