// SPDX-License-Identifier: AGPL-3.0-only
// GENERATED by tools/generate_mobile.py — edit packages/mobile and packages/design instead.
package ca.openfuel.prototype

object GeneratedSamples {
 fun stations(): List<Station> = listOf(
  Station("parkside", "Petro-Canada", "Petro-Canada", "128 Parkway", 2400, 6, 620.0f, 462.0f, true, mapOf(Grade.REGULAR to 1429, Grade.PREMIUM to 1639, Grade.DIESEL to 1529), mapOf(Grade.REGULAR to 7, Grade.PREMIUM to 7, Grade.DIESEL to 7), 0),
  Station("northline", "Shell", "Shell", "640 Cedar Avenue", 1200, 3, 820.0f, 258.0f, true, mapOf(Grade.REGULAR to 1479, Grade.PREMIUM to 1689, Grade.DIESEL to 1549), mapOf(Grade.REGULAR to 12, Grade.PREMIUM to 12, Grade.DIESEL to 12), 0),
  Station("juniper", "Husky (legacy)", "Husky", "82 Birch Street", 800, 2, 425.0f, 319.0f, true, mapOf(Grade.REGULAR to 1499, Grade.PREMIUM to 1729), mapOf(Grade.REGULAR to 18, Grade.PREMIUM to 18), 0),
  Station("westway", "Esso", "Esso", "905 River Road", 3100, 7, 780.0f, 786.0f, true, mapOf(Grade.REGULAR to 1529, Grade.PREMIUM to 1759, Grade.DIESEL to 1589), mapOf(Grade.REGULAR to 42, Grade.PREMIUM to 42, Grade.DIESEL to 42), 0),
  Station("cedar", "Mobil", "Mobil", "310 Lakeside Road", 4200, 9, 247.0f, 659.0f, true, mapOf(Grade.REGULAR to 1449, Grade.PREMIUM to 1669, Grade.DIESEL to 1519), mapOf(Grade.REGULAR to 180, Grade.PREMIUM to 180, Grade.DIESEL to 180), 40),
  Station("loop", "Chevron", "Chevron", "18 Eastbank Drive", 3400, 8, 960.0f, 543.0f, false, mapOf(Grade.REGULAR to 1559, Grade.PREMIUM to 1799, Grade.DIESEL to 1629), mapOf(Grade.REGULAR to 24, Grade.PREMIUM to 24, Grade.DIESEL to 24), 0)
 )
}
