// SPDX-License-Identifier: AGPL-3.0-only
// GENERATED by tools/generate_mobile.py — edit packages/mobile and packages/design instead.
package ca.openfuel.prototype

object DesignTokens {
 const val GREEN = 0xFF285B43
 const val INK = 0xFF20392E
 const val MUTED = 0xFF768077
 const val LINE = 0xFFE8ECE5
 const val SOFT = 0xFFF3F5EF
 const val PAPER = 0xFFFFFFFF
 const val BLUE = 0xFF4485ED
 const val BEST = 0xFFF6FAF0
 const val edge = 16
 const val rowRadius = 15
 const val goSize = 48
 const val goRadius = 14
 const val searchHeight = 59
 const val searchRadius = 19
 const val sheetRadius = 26
 const val stationName = 14
 const val priceSize = 24
 const val stationAge = 9
 const val rowPadding = 12
}
