// SPDX-License-Identifier: AGPL-3.0-only
import Foundation
import XCTest
@testable import OpenFuelCore
final class PreviewDomainTests: XCTestCase {
 func testFixtureMatchesApprovedHTML(){XCTAssertEqual(PreviewSamples.stations.map(\.id),["parkside","northline","juniper","westway","cedar","loop"]);XCTAssertEqual(PreviewSamples.stations[2].name,"Husky (legacy)");XCTAssertNil(PreviewSamples.stations[2].price(.diesel))}
 func testMoneyParsing(){XCTAssertEqual(PreviewRules.parseCents("142.9"),1429);XCTAssertEqual(PreviewRules.parseCents(" 150 "),1500);for s in ["NaN","1e2","142.99","-1","49.9","400","142,9"]{XCTAssertNil(PreviewRules.parseCents(s),s)}}
 func testStandardSorting(){XCTAssertEqual(PreviewRules.visible(PreviewSamples.stations,grade:.regular).first?.id,"parkside");XCTAssertEqual(PreviewRules.visible(PreviewSamples.stations,grade:.regular).last?.id,"cedar");XCTAssertEqual(PreviewRules.visible(PreviewSamples.stations,grade:.regular,sort:.price)[1].id,"cedar");XCTAssertEqual(PreviewRules.visible(PreviewSamples.stations,grade:.regular,sort:.nearest).first?.id,"juniper")}
 func testGradeConditionsAndSaved(){XCTAssertEqual(PreviewRules.visible(PreviewSamples.stations,grade:.diesel).count,5);XCTAssertEqual(PreviewRules.visible(PreviewSamples.stations,grade:.regular,filters:.init(radiusMetres:2000)).count,2);XCTAssertEqual(PreviewRules.visible(PreviewSamples.stations,grade:.regular,filters:.init(fresh:true)).count,5);XCTAssertEqual(PreviewRules.visible(PreviewSamples.stations,grade:.regular,query:"SHELL").first?.id,"northline");XCTAssertEqual(PreviewRules.visible(PreviewSamples.stations,grade:.regular,savedOnly:true,saved:["northline"]).count,1)}
 func testUpdateDoesNotChangeOtherGrade()throws{let s=PreviewSamples.stations[0];let x=try PreviewRules.updated(s,grade:.regular,amount:1439);XCTAssertEqual(x.age(.regular),0);XCTAssertEqual(x.age(.premium),7);XCTAssertEqual(s.price(.regular),1429)}
 func testMapsNeverSendFakeAddress(){for provider in [PreviewMaps.apple,.google]{let url=PreviewRules.sampleMapURL(PreviewSamples.stations[0],provider:provider).absoluteString;XCTAssertFalse(url.contains("Parkway"));XCTAssertFalse(url.contains("origin"));XCTAssertTrue(url.contains("Petro-Canada"))}}
 func testConfigurationRejectsCredentialsAndHTTP(){for s in ["http://example.com","https://user:secret@example.com","https://example.com/?key=private"]{XCTAssertThrowsError(try PublicAPIConfiguration(s))};XCTAssertNoThrow(try PublicAPIConfiguration("https://example.com/api/v1"))}
 func testCameraMatchesHTMLFit(){let c=PreviewCamera.fit(width:390,height:844,sheetHeight:336,stations:PreviewSamples.stations);XCTAssertEqual(c.scale,305.0/785.0,accuracy:0.000001);let x=(620-c.cx)*c.scale+195;XCTAssertGreaterThan(x,42);XCTAssertLessThan(x,347)}
 func testDraftValidation(){XCTAssertThrowsError(try PreviewDraft(stationID:nil,kind:"addition",name:"Test",latitude:Double.nan,longitude:2));XCTAssertThrowsError(try PreviewDraft(stationID:nil,kind:"permanent_closure",name:"Test"))}
 func testPersistenceRoundTrip()async throws{let url=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString);defer{try? FileManager.default.removeItem(at:url)};let store=PreviewDiskStore(directory:url);var prefs=PreviewPreferences();prefs.maps = .google;prefs.wide=true;try await store.savePreferences(prefs);let actual=try await store.loadPreferences();XCTAssertEqual(actual,prefs);let draft=try PreviewDraft(stationID:"parkside",kind:"correction",name:"Petro-Canada");try await store.saveDraft(draft);try await store.saveDraft(draft);let count=try await store.drafts().count;XCTAssertEqual(count,1);try await store.deleteDrafts();let empty=try await store.drafts();XCTAssertTrue(empty.isEmpty)}
 func testCorruptPersistenceDoesNotMasqueradeAsSaved()async throws{let url=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString);defer{try? FileManager.default.removeItem(at:url)};try FileManager.default.createDirectory(at:url,withIntermediateDirectories:true);try Data("bad json".utf8).write(to:url.appendingPathComponent("preferences.json"));let store=PreviewDiskStore(directory:url);do{_ = try await store.loadPreferences();XCTFail("Should throw")}catch{}}
}
