#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Generate data/tokens and copy ORIGINAL basemap artwork. No shared UI runtime.
PNG is a map-only asset, not a screen or UI screenshot. Rerender SVG deliberately after map edits.
"""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
rows=json.loads((ROOT/'packages/mobile/stations.json').read_text())
tokens=json.loads((ROOT/'packages/design/tokens.json').read_text())
android=ROOT/'apps/android/app/src/main'
ios=ROOT/'apps/ios'
outputs={}
header='// SPDX-License-Identifier: AGPL-3.0-only\n// GENERATED by tools/generate_mobile.py — edit packages/mobile and packages/design instead.\n'
def quote(v):return json.dumps(v,ensure_ascii=False)
k=header+'package ca.openfuel.prototype\n\nobject GeneratedSamples {\n fun stations(): List<Station> = listOf(\n'
for i,r in enumerate(rows):
 prices=', '.join(f'Grade.{g.upper()} to {v}' for g,v in r['prices'].items() if v is not None)
 ages=', '.join(f'Grade.{g.upper()} to {r["age"]}' for g,v in r['prices'].items() if v is not None)
 k+=f'  Station({quote(r["id"])}, {quote(r["name"])}, {quote(r["name"].replace(" (legacy)",""))}, {quote(r["address"])}, {r["distanceMetres"]}, {r["minutes"]}, {r["x"]}.0f, {r["y"]}.0f, {str(r["open"]).lower()}, mapOf({prices}), mapOf({ages}), {r.get("memberDiscount",0)})'+(',' if i<len(rows)-1 else '')+'\n'
k+=' )\n}\n'
outputs[android/'java/ca/openfuel/prototype/GeneratedSamples.kt']=k.encode()
k=header+'package ca.openfuel.prototype\n\nobject DesignTokens {\n'
for n,v in tokens['colour'].items():k+=f' const val {n.upper()} = 0xFF{v[1:].upper()}\n'
for n,v in tokens['layout'].items():k+=f' const val {n} = {v}\n'
k+='}\n';outputs[android/'java/ca/openfuel/prototype/GeneratedDesign.kt']=k.encode()
s=header+'import Foundation\n\npublic enum PreviewSamples {\n public static var stations: [PreviewStation] { [\n'
for i,r in enumerate(rows):
 prices=', '.join(f'"{g}": {v}' for g,v in r['prices'].items() if v is not None)
 ages=', '.join(f'"{g}": {r["age"]}' for g,v in r['prices'].items() if v is not None)
 s+=f'  PreviewStation(id: {quote(r["id"])}, name: {quote(r["name"])}, brand: {quote(r["name"].replace(" (legacy)",""))}, address: {quote(r["address"])}, distanceMetres: {r["distanceMetres"]}, minutes: {r["minutes"]}, x: {r["x"]}, y: {r["y"]}, open: {str(r["open"]).lower()}, prices: [{prices}], ages: [{ages}], memberDiscount: {r.get("memberDiscount",0)})'+(',' if i<len(rows)-1 else '')+'\n'
s+=' ] }\n}\n\npublic enum PreviewTokens {\n'
for n,v in tokens['colour'].items():s+=f' public static let {n}: UInt = 0x{v[1:].upper()}\n'
for n,v in tokens['layout'].items():s+=f' public static let {n}: Double = {v}\n'
s+='}\n';outputs[ios/'OpenFuelCore/Sources/OpenFuelCore/GeneratedPreview.swift']=s.encode()
mapbytes=(ROOT/'packages/mobile/basemap.png').read_bytes()
outputs[android/'res/drawable-nodpi/demo_basemap.png']=mapbytes
outputs[ios/'OpenFuel/Resources/demo_basemap.png']=mapbytes
# Code-compatible fixture for testing, not external geodata or station licences.
outputs[ios/'OpenFuelCore/Tests/OpenFuelCoreTests/preview-stations.json']=(ROOT/'packages/mobile/stations.json').read_bytes()
check='--check' in sys.argv
bad=[]
for path,data in outputs.items():
 if check:
  if not path.exists() or path.read_bytes()!=data:bad.append(str(path.relative_to(ROOT)))
 else:path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)
if bad:raise SystemExit('Generated mobile resources drift: '+', '.join(bad))
print(('Checked' if check else 'Generated')+f' {len(outputs)} matching mobile resources; UI remains platform-native.')
